services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/code
    environment:
      - YOUR_ENV=development

volumes:
  pgdata:
    driver: local
