services:
  py_send_message:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/code
    environment:
      - YOUR_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=py_send_message
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    command: >
      uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    environment:
      - YOUR_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=py_send_message
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      alembic upgrade head
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: py_send_message
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d py_send_message"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2-alpine
    volumes:
      - redis-data:/data

volumes:
  pgdata:
    driver: local
  redis-data:
    driver: local
