"""add outer_id in Slog

Revision ID: f66d624cdcce
Revises: 8bf87ee1a720
Create Date: 2025-04-14 22:26:24.202938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66d624cdcce'
down_revision: Union[str, None] = '8bf87ee1a720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slogs', sa.Column('outer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slogs', 'outer_id')
    # ### end Alembic commands ###
